# tls/https configuration


tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/certs/local.crt
        keyFile: /etc/ssl/certs/local.key

  certificates:
    - certFile: /etc/ssl/certs/local.crt
      keyFile: /etc/ssl/certs/local.key
      stores:
        - default
